#!/bin/sh

get_remote_repo() {
    cd $1
    git init
    git remote add origin https://github.com/$2
    git fetch
    git checkout $3
    cd -
}

get_remote_repo ~ arnie97/dotfiles conf
get_remote_repo ~/.config/zsh ohmyzsh/ohmyzsh master
mkdir -p ~/.local/share/nvim/site/autoload
wget -nc -O ~/.local/share/nvim/site/autoload/plug.vim \
    "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
wget -nc -O ~/.ssh/authorized_keys \
    "https://raw.githubusercontent.com/arnie97/dotfiles/init/authorized_keys"
